/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hsms_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class OpeningDisplay extends javax.swing.JFrame {

    /**
     * Creates new form OpeningDisplay
     */
    Connection connection = null;
    Statement statement = null;
    ResultSet resultset = null;
    
    public OpeningDisplay() {   
        initComponents();
        set_current_admin();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        societyMembersBtn = new javax.swing.JButton();
        societyFeesBtn = new javax.swing.JButton();
        donationBtn = new javax.swing.JButton();
        SocietyVehiclesBtn = new javax.swing.JButton();
        bloodRecordsBtn = new javax.swing.JButton();
        societyHallBookingBtn = new javax.swing.JButton();
        complaintsBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        editAdminPanelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        societyMembersBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        societyMembersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-queue-64.png"))); // NOI18N
        societyMembersBtn.setText(" Society Members ");
        societyMembersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                societyMembersBtnActionPerformed(evt);
            }
        });

        societyFeesBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        societyFeesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-paper-money-64.png"))); // NOI18N
        societyFeesBtn.setText(" Society Fees");
        societyFeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                societyFeesBtnActionPerformed(evt);
            }
        });

        donationBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        donationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-donation-50.png"))); // NOI18N
        donationBtn.setText("Donation");
        donationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationBtnActionPerformed(evt);
            }
        });

        SocietyVehiclesBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SocietyVehiclesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-protected-bike-lane-64.png"))); // NOI18N
        SocietyVehiclesBtn.setText(" Society Vehicles ");
        SocietyVehiclesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocietyVehiclesBtnActionPerformed(evt);
            }
        });

        bloodRecordsBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bloodRecordsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-blood-donation-64-colored.png"))); // NOI18N
        bloodRecordsBtn.setText("Blood Records");
        bloodRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodRecordsBtnActionPerformed(evt);
            }
        });

        societyHallBookingBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        societyHallBookingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-city-hall-64.png"))); // NOI18N
        societyHallBookingBtn.setText("Society Hall Booking");
        societyHallBookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                societyHallBookingBtnActionPerformed(evt);
            }
        });

        complaintsBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        complaintsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-hint-64.png"))); // NOI18N
        complaintsBtn.setText("Complaints");
        complaintsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintsBtnActionPerformed(evt);
            }
        });

        logOutBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logOutBtn.setText("Log out");
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        editAdminPanelBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editAdminPanelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database_2/icons8-admin-settings-male-64.png"))); // NOI18N
        editAdminPanelBtn.setText("Edit Admin Panel");
        editAdminPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminPanelBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons_database/background.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Admin:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logOutBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(complaintsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(societyMembersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(societyFeesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(donationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(SocietyVehiclesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bloodRecordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(societyHallBookingBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(editAdminPanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(81, 81, 81)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(societyMembersBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(societyFeesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SocietyVehiclesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(societyHallBookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(complaintsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(donationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodRecordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editAdminPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void societyMembersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_societyMembersBtnActionPerformed
        // TODO add your handling code here:
        SocietyMembers sm = new SocietyMembers();
        sm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_societyMembersBtnActionPerformed

    private void societyFeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_societyFeesBtnActionPerformed
        // TODO add your handling code here:
        SocietyFees fees = new SocietyFees();
        fees.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_societyFeesBtnActionPerformed

    private void donationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationBtnActionPerformed
        // TODO add your handling code here:
        Donation donation = new Donation();
        donation.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_donationBtnActionPerformed

    private void SocietyVehiclesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocietyVehiclesBtnActionPerformed
        // TODO add your handling code here:
        Vehicle vehicle = new Vehicle();
        vehicle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SocietyVehiclesBtnActionPerformed

    private void bloodRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodRecordsBtnActionPerformed
        // TODO add your handling code here:
        Blood blood = new Blood();
        blood.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bloodRecordsBtnActionPerformed

    private void societyHallBookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_societyHallBookingBtnActionPerformed
        // TODO add your handling code here:
        SocietyHallBooking hb = null;
        try {
            hb = new SocietyHallBooking();
        } catch (ParseException ex) {
            Logger.getLogger(OpeningDisplay.class.getName()).log(Level.SEVERE, null, ex);
        }
        hb.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_societyHallBookingBtnActionPerformed

    private void complaintsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintsBtnActionPerformed
        // TODO add your handling code here:
        complaints_Rafsan com = new complaints_Rafsan();
        com.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_complaintsBtnActionPerformed

    private void editAdminPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminPanelBtnActionPerformed
        // TODO add your handling code here:
        AdminEdit adminedit = new AdminEdit();
        adminedit.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_editAdminPanelBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        logout_current_admin();
        this.setVisible(false);
        dispose();
        Admin admin = new Admin();
        admin.setVisible(true);
        
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
     public void logout_current_admin(){
        Connection connection;
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=HSMS_Project;selectMethod=cursor", "sa", "123456");
            
            Statement statement = connection.createStatement();
            statement.executeUpdate("Update ADMIN set Active = 0 where Active = 1");
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpeningDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpeningDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpeningDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpeningDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpeningDisplay().setVisible(true);
            }
        });
    }
    
    public void set_current_admin(){
       try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=HSMS_Project;selectMethod=cursor", "sa", "123456");
            
            Statement statement = connection.createStatement();
            ResultSet resultSet = statement.executeQuery("select Username from ADMIN where Active=1");
            while (resultSet.next()) {
                String name = resultSet.getString("Username");
                jLabel3.setText(name);
                System.out.println(name);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SocietyVehiclesBtn;
    private javax.swing.JButton bloodRecordsBtn;
    private javax.swing.JButton complaintsBtn;
    private javax.swing.JButton donationBtn;
    private javax.swing.JButton editAdminPanelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton societyFeesBtn;
    private javax.swing.JButton societyHallBookingBtn;
    private javax.swing.JButton societyMembersBtn;
    // End of variables declaration//GEN-END:variables
}
